
# Numpy array. Практическая работа

## Цель практической работы

Выполните задачи, чтобы потренироваться в использовании функционала NumPy.

## Что входит в практическое задание

10 задач на использование библиотеки NumPy.


In [1]:
import numpy as np

## Что нужно сделать

Скачайте файл с заданием в материалах, откройте его через Jupyter Notebook и выполните задачи. Сверьтесь с ответами, представленными ниже. Обратите внимание, что это задание не нужно сдавать на проверку.


## Задачи


1. Создайте вектор размера 10, заполненный нулями, но пятый элемент которого равен 1.

In [2]:
# ваш код здесь
nuls = np.zeros(10)
nuls[4] = 1
nuls

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

2. Создайте вектор со значениями от 10 до 49.

In [3]:
# ваш код здесь
array_ar = np.arange(10, 50, 1)
array_ar

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

3. Создайте матрицу (двумерный массив) 3x3 со значениями от 0 до 8.

In [4]:
# ваш код здесь
matrix_np = np.arange(0,9).reshape(3,3)
matrix_np


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

4. Создайте массив 3x3x3 со случайными значениями.

In [5]:
# ваш код здесь
np.random.randint(0, 150, size=(3, 3))

array([[66, 55, 35],
       [80, 30, 34],
       [11, 54, 50]])

5. Создайте матрицу 10x10 с 0 внутри и 1 на границах.

In [6]:
# ваш код здесь
array_np = np.zeros(10*10)
array_np[0], array_np[-1] = 1, 1
array_np.reshape(10, 10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [10]:
array_np = np.ones(10*10).reshape(10, 10)
array_np[1:-1, 1:-1] = 0
array_np

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

6. Создайте матрицы  5x3 и 3x2 со случайными значениями и перемножьте их.

In [11]:
# ваш код здесь
matrix_5x3 = np.random.randint(0, 42, size=(5, 3))
matrix_3x2 = np.random.randint(0, 42, size=(3, 2))
np.dot(matrix_5x3, matrix_3x2)

array([[2140, 2090],
       [1528, 1524],
       [2358, 2420],
       [1452, 1466],
       [ 586,  588]])

Для выполнения задач 7–10 создайте массив 10x10 со значениями от 1 до 100 и все вычисления производите на нём.



In [32]:
matrix100 = np.arange(1, 101).reshape(10, 10)
matrix100

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

7. Замените максимальный элемент матрицы на ноль.

In [33]:
# ваш код здесь
matrix100[matrix100==matrix100.max()] = 0
matrix100

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
       [81, 82, 83, 84, 85, 86, 87, 88, 89, 90],
       [91, 92, 93, 94, 95, 96, 97, 98, 99,  0]])

8. Отнимите среднее из каждой строки в матрице.

In [34]:
# ваш код здесь
for ir, row in enumerate(matrix100):
    for iv, value in enumerate(row):
        matrix100[ir, iv] = matrix100[ir, iv] - row.mean()
matrix100
# matrix100 - matrix100.mean()

array([[ -4,  -3,  -1,   0,   1,   2,   4,   5,   6,   8],
       [ -4,  -2,   0,   2,   4,   7,   8,  10,  12,  14],
       [ -4,  -1,   2,   5,   8,  11,  13,  15,  18,  20],
       [ -4,   0,   4,   8,  11,  15,  18,  21,  23,  26],
       [ -4,   1,   6,  10,  15,  19,  22,  26,  29,  32],
       [ -4,   2,   8,  13,  18,  23,  27,  31,  35,  38],
       [ -4,   3,   9,  16,  22,  27,  32,  36,  41,  44],
       [ -4,   4,  11,  19,  25,  31,  37,  42,  46,  50],
       [ -4,   5,  13,  21,  29,  35,  41,  47,  52,  57],
       [  5,  15,  23,  31,  39,  45,  51,  57,  62, -32]])

9. Посчитайте сумму по последним двум осям.

In [35]:
# ваш код здесь
matrix100[-2:].sum(axis=1)

array([296, 296])

10. Поменяйте две строки в матрице.

In [36]:
# ваш код здесь
matrix100[[0,9]] = matrix100[[9,0]]
matrix100

array([[  5,  15,  23,  31,  39,  45,  51,  57,  62, -32],
       [ -4,  -2,   0,   2,   4,   7,   8,  10,  12,  14],
       [ -4,  -1,   2,   5,   8,  11,  13,  15,  18,  20],
       [ -4,   0,   4,   8,  11,  15,  18,  21,  23,  26],
       [ -4,   1,   6,  10,  15,  19,  22,  26,  29,  32],
       [ -4,   2,   8,  13,  18,  23,  27,  31,  35,  38],
       [ -4,   3,   9,  16,  22,  27,  32,  36,  41,  44],
       [ -4,   4,  11,  19,  25,  31,  37,  42,  46,  50],
       [ -4,   5,  13,  21,  29,  35,  41,  47,  52,  57],
       [ -4,  -3,  -1,   0,   1,   2,   4,   5,   6,   8]])

|

|

|

|

|

|

|

|

|

|

|

## Решения

In [ ]:
import numpy as np

1. Создать вектор размера 10, заполненный нулями, но пятый элемент которого равен 1.

In [ ]:
A = np.zeros(10)
A[5] = 1
A

2. Создать вектор со значениями от 10 до 49.

In [ ]:
A = np.arange(10, 50)
A

3. Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8.

In [ ]:
A = np.arange(9)
A = np.reshape(A, (3,3))
A

4. Создать массив 3x3x3 со случайными значениями.

In [ ]:
A = np.random.randn(27)
A = np.reshape(A, (3,3,3)) # не бойтесь брать размерность больше - сам функционал не меняется
A

5. Создать матрицу 10x10 с 0 внутри и 1 на границах.

In [ ]:
A = np.ones([10,10])
A [1:-1, 1:-1] = 0
A

6. Создать матрицы  5x3 и 3x2 со случайными значениями и перемножить их.

In [ ]:
A = np.random.randn(15)
A = np.reshape(A, (5,3))
A

In [ ]:
B = np.random.randn(6)
B = np.reshape(B, (3,2))
B

В задании не сказано, как перемножать матрицы: поэлементно или согласно правилам матричного перемножения. Так как поэлементное умножение вызовет ошибку, потому что размерности матриц не согласуются, выполним матричное перемножение:

In [ ]:
np.dot(A, B)

|

Создать массив 10x10 со значениями от 1 до 100.

In [15]:
A = np.arange(1,101)
A = np.reshape(A, (10,10))
A

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

7. Заменить максимальный элемент матрицы на ноль.

In [16]:
A[A == A.max()] = 0
A

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
       [81, 82, 83, 84, 85, 86, 87, 88, 89, 90],
       [91, 92, 93, 94, 95, 96, 97, 98, 99,  0]])

8. Отнять среднее из каждой строки в матрице.

In [17]:
A - A.mean()

array([[-48.5, -47.5, -46.5, -45.5, -44.5, -43.5, -42.5, -41.5, -40.5,
        -39.5],
       [-38.5, -37.5, -36.5, -35.5, -34.5, -33.5, -32.5, -31.5, -30.5,
        -29.5],
       [-28.5, -27.5, -26.5, -25.5, -24.5, -23.5, -22.5, -21.5, -20.5,
        -19.5],
       [-18.5, -17.5, -16.5, -15.5, -14.5, -13.5, -12.5, -11.5, -10.5,
         -9.5],
       [ -8.5,  -7.5,  -6.5,  -5.5,  -4.5,  -3.5,  -2.5,  -1.5,  -0.5,
          0.5],
       [  1.5,   2.5,   3.5,   4.5,   5.5,   6.5,   7.5,   8.5,   9.5,
         10.5],
       [ 11.5,  12.5,  13.5,  14.5,  15.5,  16.5,  17.5,  18.5,  19.5,
         20.5],
       [ 21.5,  22.5,  23.5,  24.5,  25.5,  26.5,  27.5,  28.5,  29.5,
         30.5],
       [ 31.5,  32.5,  33.5,  34.5,  35.5,  36.5,  37.5,  38.5,  39.5,
         40.5],
       [ 41.5,  42.5,  43.5,  44.5,  45.5,  46.5,  47.5,  48.5,  49.5,
        -49.5]])

9. Посчитать сумму по последним двум строкам.

In [23]:
A[-2:].sum(axis=1)

array([855, 855])

10. Поменять две строки в матрице.

Поменяем первую и последнюю строки:

In [ ]:
A[[0,9]] = A[[9,0]]
A